apiVersion: v1
kind: Pod
metadata:
  name: echo-health
  labels:
    name: echo
spec:
  containers:
    - name: app
      image: ghcr.io/subicura/echo:v1
      livenessProbe: # 존재하지 않는 곳에 요청을 넣어서 죽어버림.
        httpGet:
          path: /
          port: 3000
      readinessProbe: # 준비되었는지 체크하고, 준비되지 않았다면 Pod으로 오는 요청을 제외.
        httpGet:
          path: /
          port: 3000
